import { Inter } from "next/font/google";
import "../globals.css";
import HeaderBase from "@/components/layout/header-base";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={`${inter.className} p-4`}>
        <HeaderBase />
        {children}
      </body>
    </html>
  );
}
