export const obras = [
  {
    id: 25,
    nome: "Escola Municipal 32",
    responsavel: "Maria Santos",
    dataInicio: "03/01/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 82,
  },
  {
    id: 19,
    nome: "Escola Municipal 60",
    responsavel: "Roberto Almeida",
    dataInicio: "06/01/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 18,
  },
  {
    id: 26,
    nome: "Quadra Poliesportiva 85",
    responsavel: "Beatriz Martins",
    dataInicio: "10/01/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 6,
  },
  {
    id: 1,
    nome: "Centro Cultural 84",
    responsavel: "Carlos Ferreira",
    dataInicio: "13/01/2025",
    dataConclusao: "28/10/2025",
    dataArquivo: null,
    andamento: 100,
  },
  {
    id: 32,
    nome: "Hospital Regional 41",
    responsavel: "João Silva",
    dataInicio: "14/01/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 74,
  },
  {
    id: 6,
    nome: "Biblioteca Pública 72",
    responsavel: "João Silva",
    dataInicio: "16/01/2025",
    dataConclusao: "14/02/2025",
    dataArquivo: null,
    andamento: 100,
  },
  {
    id: 7,
    nome: "Centro Cultural 84",
    responsavel: "Carlos Ferreira",
    dataInicio: "22/01/2025",
    dataConclusao: "10/06/2025",
    dataArquivo: null,
    andamento: 100,
  },
  {
    id: 27,
    nome: "Centro de Convenções 2",
    responsavel: "Maria Santos",
    dataInicio: "23/01/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 34,
  },
  {
    id: 42,
    nome: "Centro Cultural 42",
    responsavel: "Lucia Pereira",
    dataInicio: "27/01/2025",
    dataConclusao: "30/10/2025",
    dataArquivo: "26/11/2025",
    andamento: 100,
  },
  {
    id: 5,
    nome: "Ponte Norte 49",
    responsavel: "Ana Costa",
    dataInicio: "04/02/2025",
    dataConclusao: "14/12/2025",
    dataArquivo: null,
    andamento: 100,
  },
  {
    id: 30,
    nome: "Centro Cultural 51",
    responsavel: "Roberto Almeida",
    dataInicio: "04/02/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 61,
  },
  {
    id: 47,
    nome: "Centro Cultural 83",
    responsavel: "Ana Costa",
    dataInicio: "04/02/2025",
    dataConclusao: "28/09/2025",
    dataArquivo: "19/12/2025",
    andamento: 100,
  },
  {
    id: 2,
    nome: "Parque Municipal 23",
    responsavel: "Roberto Almeida",
    dataInicio: "06/02/2025",
    dataConclusao: "03/10/2025",
    dataArquivo: null,
    andamento: 100,
  },
  {
    id: 49,
    nome: "Ponte Norte 62",
    responsavel: "Beatriz Martins",
    dataInicio: "07/02/2025",
    dataConclusao: "13/10/2025",
    dataArquivo: "28/12/2025",
    andamento: 100,
  },
  {
    id: 43,
    nome: "Terminal Rodoviário 0",
    responsavel: "Pedro Oliveira",
    dataInicio: "08/02/2025",
    dataConclusao: "09/11/2025",
    dataArquivo: "03/12/2025",
    andamento: 100,
  },
  {
    id: 16,
    nome: "Biblioteca Pública 76",
    responsavel: "Roberto Almeida",
    dataInicio: "12/02/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 17,
  },
  {
    id: 24,
    nome: "Terminal Rodoviário 3",
    responsavel: "Ana Costa",
    dataInicio: "19/02/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 64,
  },
  {
    id: 36,
    nome: "Escola Municipal 21",
    responsavel: "Roberto Almeida",
    dataInicio: "20/02/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 94,
  },
  {
    id: 31,
    nome: "Escola Municipal 64",
    responsavel: "João Silva",
    dataInicio: "23/02/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 69,
  },
  {
    id: 34,
    nome: "Escola Municipal 26",
    responsavel: "João Silva",
    dataInicio: "28/02/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 6,
  },
  {
    id: 33,
    nome: "Hospital Regional 57",
    responsavel: "Fernando Souza",
    dataInicio: "09/03/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 17,
  },
  {
    id: 9,
    nome: "Centro Cultural 2",
    responsavel: "Beatriz Martins",
    dataInicio: "11/03/2025",
    dataConclusao: "12/06/2025",
    dataArquivo: null,
    andamento: 100,
  },
  {
    id: 3,
    nome: "Centro de Convenções 18",
    responsavel: "Ana Costa",
    dataInicio: "13/03/2025",
    dataConclusao: "24/11/2025",
    dataArquivo: null,
    andamento: 100,
  },
  {
    id: 12,
    nome: "Biblioteca Pública 86",
    responsavel: "Carlos Ferreira",
    dataInicio: "17/03/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 35,
  },
  {
    id: 14,
    nome: "Escola Municipal 52",
    responsavel: "Fernando Souza",
    dataInicio: "17/03/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 36,
  },
  {
    id: 22,
    nome: "Centro de Convenções 33",
    responsavel: "Patricia Lima",
    dataInicio: "20/03/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 50,
  },
  {
    id: 10,
    nome: "Hospital Regional 96",
    responsavel: "Patricia Lima",
    dataInicio: "25/03/2025",
    dataConclusao: "20/11/2025",
    dataArquivo: null,
    andamento: 100,
  },
  {
    id: 50,
    nome: "Ponte Norte 65",
    responsavel: "Maria Santos",
    dataInicio: "01/04/2025",
    dataConclusao: "09/07/2025",
    dataArquivo: "07/08/2025",
    andamento: 100,
  },
  {
    id: 35,
    nome: "Parque Municipal 84",
    responsavel: "Carlos Ferreira",
    dataInicio: "02/04/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 81,
  },
  {
    id: 39,
    nome: "Centro de Convenções 87",
    responsavel: "Beatriz Martins",
    dataInicio: "08/04/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 77,
  },
  {
    id: 29,
    nome: "Centro Cultural 97",
    responsavel: "Patricia Lima",
    dataInicio: "12/04/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 15,
  },
  {
    id: 45,
    nome: "Praça Central 63",
    responsavel: "Pedro Oliveira",
    dataInicio: "13/04/2025",
    dataConclusao: "23/10/2025",
    dataArquivo: "04/11/2025",
    andamento: 100,
  },
  {
    id: 21,
    nome: "Praça Central 42",
    responsavel: "Ana Costa",
    dataInicio: "15/04/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 84,
  },
  {
    id: 46,
    nome: "Quadra Poliesportiva 91",
    responsavel: "Carlos Ferreira",
    dataInicio: "16/04/2025",
    dataConclusao: "09/12/2025",
    dataArquivo: "16/12/2025",
    andamento: 100,
  },
  {
    id: 48,
    nome: "Biblioteca Pública 12",
    responsavel: "Lucia Pereira",
    dataInicio: "17/04/2025",
    dataConclusao: "07/12/2025",
    dataArquivo: "13/12/2025",
    andamento: 100,
  },
  {
    id: 11,
    nome: "Parque Municipal 25",
    responsavel: "Pedro Oliveira",
    dataInicio: "20/04/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 12,
  },
  {
    id: 28,
    nome: "Ponte Norte 77",
    responsavel: "Ana Costa",
    dataInicio: "22/04/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 12,
  },
  {
    id: 41,
    nome: "Escola Municipal 11",
    responsavel: "Carlos Ferreira",
    dataInicio: "29/04/2025",
    dataConclusao: "05/09/2025",
    dataArquivo: "28/10/2025",
    andamento: 100,
  },
  {
    id: 18,
    nome: "Biblioteca Pública 93",
    responsavel: "João Silva",
    dataInicio: "01/05/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 56,
  },
  {
    id: 13,
    nome: "Quadra Poliesportiva 1",
    responsavel: "Ana Costa",
    dataInicio: "03/05/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 22,
  },
  {
    id: 15,
    nome: "Praça Central 72",
    responsavel: "João Silva",
    dataInicio: "03/05/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 21,
  },
  {
    id: 8,
    nome: "Parque Municipal 77",
    responsavel: "Lucia Pereira",
    dataInicio: "04/05/2025",
    dataConclusao: "21/08/2025",
    dataArquivo: null,
    andamento: 100,
  },
  {
    id: 20,
    nome: "Quadra Poliesportiva 73",
    responsavel: "Roberto Almeida",
    dataInicio: "06/05/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 2,
  },
  {
    id: 37,
    nome: "Praça Central 6",
    responsavel: "Beatriz Martins",
    dataInicio: "09/05/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 30,
  },
  {
    id: 44,
    nome: "Quadra Poliesportiva 56",
    responsavel: "Patricia Lima",
    dataInicio: "18/05/2025",
    dataConclusao: "25/12/2025",
    dataArquivo: "29/12/2025",
    andamento: 100,
  },
  {
    id: 23,
    nome: "Quadra Poliesportiva 0",
    responsavel: "Roberto Almeida",
    dataInicio: "20/05/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 79,
  },
  {
    id: 38,
    nome: "Centro Cultural 88",
    responsavel: "Fernando Souza",
    dataInicio: "20/05/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 34,
  },
  {
    id: 4,
    nome: "Escola Municipal 23",
    responsavel: "Maria Santos",
    dataInicio: "24/05/2025",
    dataConclusao: "05/11/2025",
    dataArquivo: null,
    andamento: 100,
  },
  {
    id: 17,
    nome: "Parque Municipal 11",
    responsavel: "Roberto Almeida",
    dataInicio: "28/05/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 72,
  },
  {
    id: 40,
    nome: "Ponte Norte 3",
    responsavel: "Carlos Ferreira",
    dataInicio: "28/05/2025",
    dataConclusao: null,
    dataArquivo: null,
    andamento: 75,
  },
];
