import HeaderMobile from "@/components/layout/header-mobile";
import "../globals.css";
import HeaderBase from "@/components/layout/header-base";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <HeaderBase/>
        <HeaderMobile/>
        {children}
      </body>
    </html>
  );
}
